### ISSUE TITLE
General things i've noticed

### ISSUE THREAD

**Issue by ZaneWentInsane** [ampersanditbandit/Voidsong-Minecraft-Mod#4]
### **- Balancing problems:**
~Voided tools have no right to do that amount of damage, I managed to go through the entire pack with only iron armor and a diamond axe without any issues. Along with how rare the ore is, I spent an hour going through Missing biomes and I only got 1, I could just be unlucky though
~Ashlands are extremely common, taking up over half the world, this may be intentional, but it is too bare, and far to repetitive to be worth taking up that much space.
~Factory loot... 3 factories I had found in under 10 minutes had offered me over 5 stacks of iron and enough diamonds to make an axe, the same axe I beat the mod with; this is obtainable immediately, and seems way too easy for the health of the enemies (Guardians are almost 3 shot with crits from an axe.)
### **- Some spelling corrections:** 
~Notfound seems intentional, so I wont bother with that one.
~GUARDIAN being all caps seems unneeded, not even having a boss bar, it seems overhyped for what is currently is.
~MissingOre, MissingIngot and Block of MissingOre should probably have spaces after "Missing," I get what you're doing, but instead of seeming glitchy, or unusual, it seems like a mistake. (No offence, this is coming from my years as a playtester, and I am only giving my honest opinions on a few small things.)
~DeadWood should probably be Dead Wood, Ashen Oak, Dead Oak,  something along the lines of that, this one isn't too bad either way, still unsure which one actually looks better, I wouldn't worry about this one.
### **- Enemy spawning:**
~After entering a Starlit cave, some wandering led me to find two Guardian hearts on the ground, because they had suffocated in the roof of the cave, this is an issue, as with the collection of Enshrouded Spectator blocks being extremely easy, this is a large balancing problem for the Guardian Armor set, which dwarfs netherite easily in defense.
~Regardless of where you are, even if you are not actually in the biome, if the game detects that you are, for example in a vanilla cave under an Ashlands, the only enemy that can spawn is Monoids, this is the same for every other biome, it completly stops every other enemy from spawning, even if the player is not visibly in the biome; for example, I was chilling outside a Missing biome with some Monoids at y-38 in a normal cave, completely safe.
~The Guardian could use a new spawning mechanic, it seems not common, but out of place in where it spawns 90% of the time; on top of that, all I had to do was pillar 4 blocks and poke this guy while he could do nothing about it, and I wasn't hit once.
 ### **-Misc:**
~Missing biome kept playing it's music over other soundtracks in the game after death until relog
~Monoids do not count towards monster hunter achievement, I do not know if this is the case for other mobs
~Modded woods, such as DeadWood cannot be used to make things such as crafting tables in its plank form, as such I used it as stick fodder, while I had to travel across the biome to find an oak tree to craft a bucket.
~New items, such as different helmets, armor types, and weapons, regardless of their use is always nice, I'm sure you're already on this, like uses for the large majority of items in the mod, so I will say nothing more of it.
~More mobs of course need to be added, I understand that this is tedious, but some passive animals and such is much aprechiated, as I was living off rotten flesh from Monoids, as there is no other food I could rely on; possibly MRE's from the factories, or irradiated/corrupted food types could be cool, maybe even a Void's Delight mod in the future? Food mods are fun.
~The transition between soundtracks is very sharp, I suggest more of a fade between songs, and maybe adding some other soundtracks that could play at random, as they are very well made, but repetitive after a while.

I'm open as a playtester/suggestion guy if needed, again I'm experienced in this kind of thing, not coding, but the overall uniqueness of mods and how some could be better. If you are interested, add my discord: " zanearakai "
(once more, no offence to what you've done, this is amazing as a first mod, and I only wish to see it polish into something that people will love playing in the future)

**Comment by ampersanditbandit** [comment]
Tysm for your feedback! I’ll try to fix as much as the engine allows me to, and I HEAVILY agree with the voided item debuff. Guardians have also been an issue for a bit to deal with. As far as things like music playing over other biomes, I’m pretty sure that’s a MCreator bug? Idk because this is my first time using it.

**Comment by ampersanditbandit** [comment]
ok i've begun working on fixes

-Notfound not changed since it makes more sense for the block
-Guardian renamed to Monomati (mono - one | mati - eye (greek)
-Missing ore naming fixed
-dead wook naming fixed
-Monomati (gaurdian) shrunk & less frequent
-im not entirely sure how to fix the mob spawning everywhere issue but if i can figure it out i will
-missing biome music is an mcreator bug i think but i'll temporarily remove it for now
-monster hunter achievement is weird but likely because of mcreator issues
-deadwood crafting table recipe i forgot to add, mb
-more passive animals are planned
-MRE's are being added rn you're a genious i didnt think of that lol
-soundtrack transition is an mcreator problem and i've been looking into random music
-also balanced things (voided items nerfed, ashen wastelands now spawn in higher temperatures and constantly rain, factory loot entirely revamped
